#!/usr/bin/env bash

set -e

echo "===> Bundling..."
script/bootstrap --quiet

echo "===> Running specs..."
bundle exec rspec

if [ "$1" = "--skip-rubocop" ]; then
  echo "===> Skipping code analysis..."
else
  echo "===> Running code analysis..."
  bundle exec rubocop -f simple
fi
